import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserStatus from "./UserStatus";
import { AppSidebar } from "@/components/layout/AppSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Family & Friends Organizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
      >
        {/* HEADER */}
        <header className="flex h-16 items-center justify-between border-b bg-white/60 px-6 shadow-sm backdrop-blur">
          <h1 className="font-semibold text-[#3b4a5c] tracking-tight">
            Family & Friends Organizer
          </h1>
          <UserStatus />
        </header>

        {/* SIDEBAR + CONTENT */}
        <div className="flex min-h-[calc(100vh-4rem)]">
          {/* Desktop Sidebar */}
          <AppSidebar />

          {/* Main content */}
          <main className="flex-1 px-4 py-6 md:px-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
